package com.ficufi.copapuebla.interfaz.tabla;

import com.ficufi.copapuebla.back.service.EquipoService;
import com.ficufi.copapuebla.back.service.dto.EquipoDto;
import java.util.List;
import javax.annotation.PostConstruct;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Lazy;
import org.springframework.stereotype.Component;

/**
 *
 * @author antonio-lap
 */
@Component
@Lazy
public class EquipoTabla extends javax.swing.JPanel {
    
    private TableModel tableModel;
    
    @Autowired
    private EquipoService equipoService;

    /**
     * Creates new form EquipoTabla
     */
    public EquipoTabla() {
        initComponents();
    }
    
    @PostConstruct
    public void init() {
        tableModel = tablaEquipo.getModel();
        llenatabla();
    }
    
    public void llenatabla() {
        for (EquipoDto equipoDto : equipoService.enuentra(null)) {
            ((DefaultTableModel)tableModel).addRow(new Object[]{equipoDto.getNombre(), 
                equipoDto.getCategoria(), equipoDto.getId()});
        }        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaEquipo = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        tablaEquipo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Categoría", "Id"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaEquipo);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaEquipo;
    // End of variables declaration//GEN-END:variables
}
