package com.ficufi.copapuebla.interfaz.dialogos;

import com.ficufi.copapuebla.back.service.EquipoService;
import com.ficufi.copapuebla.back.service.dto.EquipoDto;
import com.ficufi.copapuebla.interfaz.Principal;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
 *
 * @author antonio-lap
 */
@Component
public class EquipoDialogo extends javax.swing.JPanel {
    
    @Autowired
    private EquipoService equipoService;

    @Autowired
    private Principal propietario;
    
    private JDialog dialogo;
    
    /**
     * Creates new form EquipoDialogo
     */
    public EquipoDialogo() {
        initComponents();
    }
    
    public void muestraDialogo() {
        if (dialogo == null || dialogo.getOwner() != propietario) {            
            dialogo = new JDialog(propietario, true);
            dialogo.add(this);
            dialogo.setTitle("Nuevo Categoria");
            dialogo.getRootPane().setDefaultButton(botonCancelar);
            dialogo.pack();
            dialogo.setResizable(false);
            dialogo.setLocationRelativeTo(propietario);
            }
        dialogo.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelCentral = new javax.swing.JPanel();
        etiquetaEquipo = new javax.swing.JLabel();
        textEquipo = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        panelBotones = new javax.swing.JPanel();
        botonCrear = new javax.swing.JButton();
        botonCancelar = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        panelCentral.setLayout(new java.awt.GridBagLayout());

        etiquetaEquipo.setText("Nombre Equipo:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        panelCentral.add(etiquetaEquipo, gridBagConstraints);

        textEquipo.setColumns(25);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(7, 14, 7, 7);
        panelCentral.add(textEquipo, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        panelCentral.add(jSeparator1, gridBagConstraints);

        add(panelCentral, java.awt.BorderLayout.CENTER);

        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 8, 8);
        flowLayout1.setAlignOnBaseline(true);
        panelBotones.setLayout(flowLayout1);

        botonCrear.setText("Crear");
        botonCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCrearActionPerformed(evt);
            }
        });
        panelBotones.add(botonCrear);

        botonCancelar.setText("Cancelar");
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });
        panelBotones.add(botonCancelar);

        add(panelBotones, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void botonCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCrearActionPerformed
        String equipo = textEquipo.getText().trim();
        if (equipo.isEmpty() || equipo.length() <= 3 || equipo.length() >= 50) {
            JOptionPane.showMessageDialog(dialogo, "Número de caracteres invalidos\nDebe ser mayor a 3 y menor a 50", 
                "Error de escritura", JOptionPane.ERROR_MESSAGE);
            return ;
        }        
        dialogo.setVisible(false);        
        EquipoDto equipoDto = new EquipoDto();
        equipoDto.setNombre(textEquipo.getText());
        equipoService.crear(equipoDto);
        textEquipo.setText("");
    }//GEN-LAST:event_botonCrearActionPerformed

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed
        dialogo.setVisible(false);
        textEquipo.setText("");        
    }//GEN-LAST:event_botonCancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCancelar;
    private javax.swing.JButton botonCrear;
    private javax.swing.JLabel etiquetaEquipo;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel panelBotones;
    private javax.swing.JPanel panelCentral;
    private javax.swing.JTextField textEquipo;
    // End of variables declaration//GEN-END:variables
}
