/*
 * Copyright (C) 2015 Antonio Francisco Alonso Valerdi
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package com.ficufi.copapuebla.interfaz.dialogos;

import com.ficufi.copapuebla.back.service.EquipoService;
import com.ficufi.copapuebla.back.service.JugadorService;
import com.ficufi.copapuebla.back.dto.EquipoDto;
import com.ficufi.copapuebla.back.dto.JugadorDto;
import com.ficufi.copapuebla.back.dto.TorneoDto;
import com.ficufi.copapuebla.interfaz.Principal;
import java.awt.CardLayout;
import java.awt.Dimension;
import java.io.IOException;
import java.net.URL;
import java.util.LinkedList;
import java.util.List;
import java.util.Set;
import java.util.TreeSet;
import javax.annotation.PostConstruct;
import javax.swing.AbstractListModel;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.ListCellRenderer;
import javax.swing.table.DefaultTableModel;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Lazy;
import org.springframework.stereotype.Component;

/**
 *
 * @author Antonio Francisco Alonso Valerdi
 */
@Component
@Lazy
public class JugadorEquipoDialogo extends javax.swing.JPanel {
    
    private enum Estado {EQUIPO, JUGADOR};
    
    private final Logger log = LoggerFactory.getLogger(getClass());
    private TorneoDto torneoDto;
    private EquipoDto equipoDto;
    private List<Integer> listaJugadores;
    private JDialog dialogo;    
    private ModeloListaEquipo modeloListaEquipo;
    private Estado estado;
    
    @Autowired
    private Principal propietario;
    
    @Autowired
    private EquipoService equipoService;
    
    @Autowired
    private JugadorService jugadorService;

    /**
     * Creates new form JuadorEquipoDialogo
     */
    public JugadorEquipoDialogo() {
        modeloListaEquipo = new ModeloListaEquipo();
        initComponents();        
    }
    
    @PostConstruct
    public void init() {
        estado = Estado.EQUIPO;
        listaEquipo.setCellRenderer(new RenderListaEquipo());        
        URL resource = getClass().getResource("/mensajes/relaciona_equipo.html");
        try {
            panelEditorPasos.setPage(resource);
        } catch (IOException ex) {
            log.error("No se pudo cargar la vista:{}", "/mensajes/relaciona_equipo.html");
        }
    }
    
    public void muestraDialogo() {        
        if (dialogo == null || dialogo.getOwner() != propietario) {            
            dialogo = new JDialog(propietario, true);
            dialogo.add(this);
            dialogo.setTitle("Agregar un equipo");
            dialogo.getRootPane().setDefaultButton(botonCancelar);
            dialogo.setPreferredSize(new Dimension(700, 500));
            dialogo.pack();
            dialogo.setLocationRelativeTo(propietario);
            llenaListaEquipo();
            }
        dialogo.setVisible(true);
    }
    
    private void llenaListaEquipo() {
        campoTextoTorneo.setText(torneoDto.getNombre());
        for (EquipoDto equipoDto2 : equipoService.enuentra(null)) {
            modeloListaEquipo.add(equipoDto2);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelCentral = new javax.swing.JPanel();
        panelAgredaEquipo = new javax.swing.JPanel();
        etiquetaTorneo = new javax.swing.JLabel();
        campoTextoTorneo = new javax.swing.JTextField();
        etiquetaEquipo = new javax.swing.JLabel();
        scrollPaneListaEquipo = new javax.swing.JScrollPane();
        listaEquipo = new javax.swing.JList();
        panelAgregarJugador = new javax.swing.JPanel();
        etiquetaSeleccionarJugador = new javax.swing.JLabel();
        scrollSeleccionJugador = new javax.swing.JScrollPane();
        tablaSeleccionJugador = new javax.swing.JTable();
        etiquetaJugadoresSeleccionados = new javax.swing.JLabel();
        scrollJugadoresSeleccionados = new javax.swing.JScrollPane();
        tablaJugadoresSeleccionados = new javax.swing.JTable();
        panelBotonesSeleccion = new javax.swing.JPanel();
        botonDescartar = new javax.swing.JButton();
        botonAgregarJugador = new javax.swing.JButton();
        panelBotones = new javax.swing.JPanel();
        botonAtras = new javax.swing.JButton();
        botonSiguiente = new javax.swing.JButton();
        botonAceptar = new javax.swing.JButton();
        botonCancelar = new javax.swing.JButton();
        botonAyuda = new javax.swing.JButton();
        panelPasos = new javax.swing.JPanel();
        panelEditorScroll = new javax.swing.JScrollPane();
        panelEditorPasos = new javax.swing.JEditorPane();

        setLayout(new java.awt.BorderLayout());

        panelCentral.setPreferredSize(new java.awt.Dimension(420, 320));
        panelCentral.setLayout(new java.awt.CardLayout());

        panelAgredaEquipo.setLayout(new java.awt.GridBagLayout());

        etiquetaTorneo.setText("Torneo:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 0, 0);
        panelAgredaEquipo.add(etiquetaTorneo, gridBagConstraints);

        campoTextoTorneo.setEditable(false);
        campoTextoTorneo.setColumns(30);
        campoTextoTorneo.setToolTipText("Torneo al cual se le agregará el equipo");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 330;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 24, 0, 0);
        panelAgredaEquipo.add(campoTextoTorneo, gridBagConstraints);

        etiquetaEquipo.setText("Equipo:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 0, 0);
        panelAgredaEquipo.add(etiquetaEquipo, gridBagConstraints);

        listaEquipo.setModel(modeloListaEquipo);
        listaEquipo.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listaEquipo.setToolTipText("Seleccione un equipo al cual agregar al torneo");
        listaEquipo.setPreferredSize(new java.awt.Dimension(200, 100));
        scrollPaneListaEquipo.setViewportView(listaEquipo);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 450;
        gridBagConstraints.ipady = 151;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(6, 24, 20, 12);
        panelAgredaEquipo.add(scrollPaneListaEquipo, gridBagConstraints);

        panelCentral.add(panelAgredaEquipo, "cardEquipo");

        panelAgregarJugador.setLayout(new java.awt.GridBagLayout());

        etiquetaSeleccionarJugador.setText("Seleccionar Jugador:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 4, 0);
        panelAgregarJugador.add(etiquetaSeleccionarJugador, gridBagConstraints);

        tablaSeleccionJugador.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Apellido Paterno", "Apellido Materno", "Id"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrollSeleccionJugador.setViewportView(tablaSeleccionJugador);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.1;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 12, 0, 4);
        panelAgregarJugador.add(scrollSeleccionJugador, gridBagConstraints);

        etiquetaJugadoresSeleccionados.setText("Juadores Seleccionados:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 6, 0, 0);
        panelAgregarJugador.add(etiquetaJugadoresSeleccionados, gridBagConstraints);

        tablaJugadoresSeleccionados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nomnre", "Apellido Paterno", "Apellido Paterno", "Id"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrollJugadoresSeleccionados.setViewportView(tablaJugadoresSeleccionados);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 12, 8, 4);
        panelAgregarJugador.add(scrollJugadoresSeleccionados, gridBagConstraints);

        panelBotonesSeleccion.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        botonDescartar.setText("Descartar");
        botonDescartar.setEnabled(false);
        botonDescartar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDescartarActionPerformed(evt);
            }
        });
        panelBotonesSeleccion.add(botonDescartar);

        botonAgregarJugador.setText("Agregar");
        botonAgregarJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarJugadorActionPerformed(evt);
            }
        });
        panelBotonesSeleccion.add(botonAgregarJugador);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        panelAgregarJugador.add(panelBotonesSeleccion, gridBagConstraints);

        panelCentral.add(panelAgregarJugador, "panelJugador");

        add(panelCentral, java.awt.BorderLayout.CENTER);

        panelBotones.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 7, 7));

        botonAtras.setText("Atras");
        botonAtras.setEnabled(false);
        botonAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAtrasActionPerformed(evt);
            }
        });
        panelBotones.add(botonAtras);

        botonSiguiente.setText("Siguiente");
        botonSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSiguienteActionPerformed(evt);
            }
        });
        panelBotones.add(botonSiguiente);

        botonAceptar.setText("Aceptar");
        botonAceptar.setEnabled(false);
        botonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarActionPerformed(evt);
            }
        });
        panelBotones.add(botonAceptar);

        botonCancelar.setText("Cancelar");
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });
        panelBotones.add(botonCancelar);

        botonAyuda.setText("Ayuda");
        panelBotones.add(botonAyuda);

        add(panelBotones, java.awt.BorderLayout.PAGE_END);

        panelPasos.setLayout(new java.awt.BorderLayout());

        panelEditorPasos.setEditable(false);
        panelEditorScroll.setViewportView(panelEditorPasos);

        panelPasos.add(panelEditorScroll, java.awt.BorderLayout.CENTER);

        add(panelPasos, java.awt.BorderLayout.LINE_START);
    }// </editor-fold>//GEN-END:initComponents

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed
        ((DefaultTableModel)tablaJugadoresSeleccionados.getModel()).setRowCount(0);
        ((DefaultTableModel)tablaSeleccionJugador.getModel()).setRowCount(0);
        listaEquipo.removeAll();
        dialogo.setVisible(false);
    }//GEN-LAST:event_botonCancelarActionPerformed

    private void botonSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSiguienteActionPerformed
        switch (estado) {
            case EQUIPO:
                Object object = listaEquipo.getSelectedValue();
                if (object == null) {
                    JOptionPane.showMessageDialog(dialogo, "Debe seleccionar un equipo almenos", "Error de Selección", JOptionPane.ERROR_MESSAGE);
                    return ;
                }
                equipoDto = (EquipoDto)listaEquipo.getSelectedValue();
                CardLayout cardLayout = (CardLayout)panelCentral.getLayout();
                cardLayout.show(panelCentral,"panelJugador");
                for (JugadorDto jugadorDto : jugadorService.encuentra(null)) {
                    ((DefaultTableModel)tablaSeleccionJugador.getModel()).addRow(new Object[]{jugadorDto.getNombre(), jugadorDto.getApellidoPaterno(),
                    jugadorDto.getApellidoMaterno(), jugadorDto.getId()});
                }
                botonAtras.setEnabled(true);
                botonAceptar.setEnabled(true);
                estado = Estado.JUGADOR;
                break;
            case JUGADOR:
                
                break;
            default:
                log.error("Opcion un no manejada:{}",estado);
        }
                
    }//GEN-LAST:event_botonSiguienteActionPerformed

    private void botonAgregarJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarJugadorActionPerformed
        int seleccionado = tablaSeleccionJugador.getSelectedRow();
        Object[] objects = new Object[tablaSeleccionJugador.getColumnCount()];
        if (seleccionado != -1) {
            for (int i = 0; i < tablaSeleccionJugador.getColumnCount(); i++) {
                objects[i] = tablaSeleccionJugador.getValueAt(seleccionado, i);
            }
            ((DefaultTableModel)tablaJugadoresSeleccionados.getModel()).addRow(objects);
            ((DefaultTableModel)tablaSeleccionJugador.getModel()).removeRow(seleccionado);
        }        
        if (!botonDescartar.isEnabled()) {
            botonDescartar.setEnabled(true);
        }
    }//GEN-LAST:event_botonAgregarJugadorActionPerformed

    private void botonDescartarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDescartarActionPerformed
        int seleccionado = tablaJugadoresSeleccionados.getSelectedRow();        
        if (seleccionado != -1) {
            Object[] objects = new Object[tablaSeleccionJugador.getColumnCount()];
            for (int i = 0; i < tablaSeleccionJugador.getColumnCount(); i++) {
                objects[i] = tablaJugadoresSeleccionados.getValueAt(seleccionado, i);
            }
            ((DefaultTableModel)tablaSeleccionJugador.getModel()).addRow(objects);
            ((DefaultTableModel)tablaJugadoresSeleccionados.getModel()).removeRow(seleccionado);
        }        
        if (tablaJugadoresSeleccionados.getRowCount() == 0) {
            botonDescartar.setEnabled(false);
        }
    }//GEN-LAST:event_botonDescartarActionPerformed

    private void botonAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAtrasActionPerformed
        switch (estado) {
            case JUGADOR:
                CardLayout cardLayout = (CardLayout)panelCentral.getLayout();
                cardLayout.show(panelCentral,"cardEquipo");
                estado = Estado.EQUIPO;
                botonAceptar.setEnabled(false);
                botonAtras.setEnabled(false);
                break;
            default:
                log.error("Opcion un no manejada:{}",estado);
        }
    }//GEN-LAST:event_botonAtrasActionPerformed

    private void botonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonAceptarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAceptar;
    private javax.swing.JButton botonAgregarJugador;
    private javax.swing.JButton botonAtras;
    private javax.swing.JButton botonAyuda;
    private javax.swing.JButton botonCancelar;
    private javax.swing.JButton botonDescartar;
    private javax.swing.JButton botonSiguiente;
    private javax.swing.JTextField campoTextoTorneo;
    private javax.swing.JLabel etiquetaEquipo;
    private javax.swing.JLabel etiquetaJugadoresSeleccionados;
    private javax.swing.JLabel etiquetaSeleccionarJugador;
    private javax.swing.JLabel etiquetaTorneo;
    private javax.swing.JList listaEquipo;
    private javax.swing.JPanel panelAgredaEquipo;
    private javax.swing.JPanel panelAgregarJugador;
    private javax.swing.JPanel panelBotones;
    private javax.swing.JPanel panelBotonesSeleccion;
    private javax.swing.JPanel panelCentral;
    private javax.swing.JEditorPane panelEditorPasos;
    private javax.swing.JScrollPane panelEditorScroll;
    private javax.swing.JPanel panelPasos;
    private javax.swing.JScrollPane scrollJugadoresSeleccionados;
    private javax.swing.JScrollPane scrollPaneListaEquipo;
    private javax.swing.JScrollPane scrollSeleccionJugador;
    private javax.swing.JTable tablaJugadoresSeleccionados;
    private javax.swing.JTable tablaSeleccionJugador;
    // End of variables declaration//GEN-END:variables

    private class RenderListaEquipo extends JLabel implements ListCellRenderer<EquipoDto> {

        public RenderListaEquipo() {
            setOpaque(true);
        }

        @Override
        public java.awt.Component getListCellRendererComponent(JList<? extends EquipoDto> list, EquipoDto value, int index, boolean isSelected, boolean cellHasFocus) {
            if (isSelected) {
                setBackground(list.getSelectionBackground());
                setForeground(list.getSelectionForeground());
            } else {
                setBackground(list.getBackground());
                setForeground(list.getForeground());
            }
            setText(value.getNombre());
            return this;
        }
        
    }

    private class ModeloListaEquipo extends AbstractListModel<EquipoDto> {
        
        private final Set<EquipoDto> equipos;

        public ModeloListaEquipo() {
            equipos = new TreeSet<>();
        }

        @Override
        public int getSize() {
            return equipos.size();
        }

        @Override
        public EquipoDto getElementAt(int index) {
            List<EquipoDto> list = new LinkedList<>(equipos);
            return list.get(index);
        }
        
        public void add (EquipoDto equipoDto) {
            equipos.add(equipoDto);
        }
    }

    public void setTorneoDto(TorneoDto torneoDto) {
        this.torneoDto = torneoDto;
    }
    
}
