package com.ficufi.copapuebla.interfaz.dialogos;

import com.ficufi.copapuebla.back.service.TorneoService;
import com.ficufi.copapuebla.interfaz.menu.MenuTorneo;
import java.awt.Frame;
import javax.annotation.PostConstruct;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
 * Dialogo para crear un nuevo torneo
 * @author Antonio Francisc Alonso Valerdi
 */
@Component
public class NuevoTorneoDialogo extends javax.swing.JPanel {
    
    private JDialog dialogo;
    
    @Autowired
    private Frame propietario;
    
    @Autowired
    private MenuTorneo menuTorneo;
    
    @Autowired
    private TorneoService torneoService;
    
    public void muestraDialogo() {        
        if (dialogo == null || dialogo.getOwner() != propietario) {            
            dialogo = new JDialog(propietario, true);
            dialogo.add(this);
            dialogo.setTitle("Nuevo Torneo");
            dialogo.getRootPane().setDefaultButton(botonCancelar);
            dialogo.pack();
            dialogo.setLocationRelativeTo(propietario);
            }        
        dialogo.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    @PostConstruct
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        etiquetaNuevoTorneo = new javax.swing.JLabel();
        textFieldTorneo = new javax.swing.JTextField();
        panelBotones = new javax.swing.JPanel();
        botonCrear = new javax.swing.JButton();
        botonCancelar = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        setLayout(new java.awt.BorderLayout());

        etiquetaNuevoTorneo.setText("Escribe el nombre del nuevo Torneo");
        etiquetaNuevoTorneo.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 1, 3, 5));
        add(etiquetaNuevoTorneo, java.awt.BorderLayout.PAGE_START);
        add(textFieldTorneo, java.awt.BorderLayout.CENTER);

        panelBotones.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        botonCrear.setText("Crear");
        botonCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCrearActionPerformed(evt);
            }
        });
        panelBotones.add(botonCrear);

        botonCancelar.setText("Cancelar");
        botonCancelar.setToolTipText("");
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });
        panelBotones.add(botonCancelar);

        add(panelBotones, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void botonCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCrearActionPerformed
        String torneo = textFieldTorneo.getText();
        if (torneo.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No contiene Ningun nombre", "Error de escritura", JOptionPane.ERROR_MESSAGE);
            return ;
        }
        torneoService.crearTorneo(textFieldTorneo.getText());
        menuTorneo.updateTorneo();
        dialogo.setVisible(false);
        textFieldTorneo.setText("");
    }//GEN-LAST:event_botonCrearActionPerformed

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed
        dialogo.setVisible(false);
        textFieldTorneo.setText("");
    }//GEN-LAST:event_botonCancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCancelar;
    private javax.swing.JButton botonCrear;
    private javax.swing.JLabel etiquetaNuevoTorneo;
    private javax.swing.JPanel panelBotones;
    private javax.swing.JTextField textFieldTorneo;
    // End of variables declaration//GEN-END:variables
}
